services:
  api:
    build: .
    image: dm-api:v1
    environment:
      - PORT=5000
    ports:
      - "5000:5000"

  swagger:
    image: swaggerapi/swagger-ui:latest
    environment:
      - SWAGGER_JSON=/openapi/openapi.yaml
    volumes:
      - ./openapi:/usr/share/nginx/html/openapi:ro
    ports:
      - "8080:8080"
    depends_on:
      - api

  postgres-db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mon-projet-db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d

volumes:
  db-data:
