version: "3.9"

services:
  api:
    build: ./api
    image: dm-api:v1
    environment:
      - PORT=5000
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=projet_renforcement
      - DB_HOST=postgres-db
    ports:
      - "5001:5000"
    depends_on:
      - postgres-db
    networks:
      - backend

  swagger:
    image: swaggerapi/swagger-ui:latest
    environment:
      - SWAGGER_JSON=/openapi/openapi.yaml
    volumes:
      - ./openapi:/openapi:ro
    ports:
      - "8081:8080"
    depends_on:
      - api
    networks:
      - backend

  postgres-db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=projet_renforcement
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./api/db:/docker-entrypoint-initdb.d
    networks:
      - backend

  test:
    build: ./api
    depends_on:
      - postgres-db
    command: npm test
    environment:
      - DB_HOST=postgres-db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=projet_renforcement
    networks:
      - backend

volumes:
  db-data:

networks:
  backend:
