openapi: 3.0.3
info:
  title: Dernier Metro API
  version: 1.0.0
  description: API pour gérer les stations de métro

servers:
  - url: http://localhost:5000
    description: Serveur local

paths:
  /stations:
    get:
      summary: Récupérer toutes les stations
      responses:
        '200':
          description: Liste des stations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Station'

    post:
      summary: Créer une nouvelle station
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StationInput'
      responses:
        '201':
          description: Station créée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Station'

  /stations/{id}:
    get:
      summary: Récupérer une station par ID
      parameters:
        - name: id
          in: path
          description: ID de la station
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Station trouvée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Station'
        '404':
          description: Station non trouvée

    put:
      summary: Modifier une station
      parameters:
        - name: id
          in: path
          description: ID de la station à modifier
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StationInput'
      responses:
        '200':
          description: Station mise à jour
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Station'
        '404':
          description: Station non trouvée

    delete:
      summary: Supprimer une station
      parameters:
        - name: id
          in: path
          description: ID de la station à supprimer
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Station supprimée
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Station non trouvée

components:
  schemas:
    Station:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        ligne:
          type: string
    StationInput:
      type: object
      required:
        - name
        - ligne
      properties:
        name:
          type: string
        ligne:
          type: string
